### PR TITLE
Corrected the work of C button

### PR DESCRIPTION
**Pull request by letsintegreat**
The behavior of the <kbd>C</kbd> button was not defined, so it was just appending a `C` char at the end of the screen, which is not expected.

So, I've corrected the working of <kbd>C</kbd> button, so it now clears the screen on click, which is expected.

Also, There is no need to add a closing tag for `<input>` tags, thus removed the closing tag, i.e., `</input>`

### CODE REVIEW

**Comment by HarshitSeksaria** [comment]
#4

**Comment by HarshitSeksaria** [comment]
Label: #4

**Comment by LeCeee** [comment]
#5 Well the C button is not supposed to clear the screen. The AC button does that. 
C is used to erase the recently entered character. 
See if you can fix that.

**Comment by HarshitSeksaria** [comment]
Yes, I can surely do that, Wait for a couple of minutes

**Comment by letsintegreat** [comment]
I've set the working of <kbd>C</kbd> button as per the requirements

Review this commit: https://github.com/LeCeee/calC/pull/5/commits/b54f56fdff414c345b5c85734d8f08503a9123cb

**Comment by LeCeee** [comment]
Yup, exactly what I was looking for. Merging the PR.

**Pull request merged**
